GameStore.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GameStore.Domain.Entities;

namespace GameStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

GameStore.WebUI/Models/GamesListViewModel.cs
using GameStore.Domain.Entities;
using System.Collections.Generic;

namespace GameStore.WebUI.Models
{
    public class GamesListViewModel
    {
        public IEnumerable<Game> Games { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

GameStore.WebUI/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GameStore.WebUI.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

GameStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GameStore.WebUI.Models
{
    public class PagingInfo
    {
        // Кол-во товаров
        public int TotalItems { get; set; }

        // Кол-во товаров на одной странице
        public int ItemsPerPage { get; set; }

        // Номер текущей страницы
        public int CurrentPage { get; set; }

        // Общее кол-во страниц
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

GameStore.WebUI/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.WebUI.Infrastructure;
using GameStore.WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class AccountController : Controller
    {
        private IAuthProvider authProvider;
        public AccountController(IAuthProvider provider)
        {
            authProvider = provider;
        }
        // GET: Account
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel credentials, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(credentials.UserName, credentials.Password))
                {
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                }

                ModelState.AddModelError("", "Credentials are invalid");                
            }
            return View();
        }
    }
}

GameStore.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Domain.Abstract;
using GameStore.Domain.Entities;

namespace GameStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IGameRepository repository;

        public AdminController(IGameRepository repo)
        {
            repository = repo;
        }
        // GET: Admin
        public ViewResult Index()
        {
            return View(repository.Games);
        }

        public ViewResult Edit(int gameId)
        {
            var game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);
            return View(game);
        }

        [HttpPost]
        public ActionResult Edit(Game game)
        {
            if (!ModelState.IsValid) return View(game);

            repository.SaveGame(game);
            TempData["message"] = $"Changes in game {game.Name} has been saved";
            return RedirectToAction("Index");
        }

        public ViewResult Create()
        {
            return View("Edit", new Game());
        }

        [HttpPost]
        public ActionResult Delete(int gameId)
        {
            var game = repository.DeleteGame(gameId);
            if (game != null)
            {
                TempData["message"] = $"Game {game.Name} deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

GameStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Domain.Abstract;
using GameStore.Domain.Entities;
using GameStore.WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IGameRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IGameRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        // GET: Cart
        public RedirectToRouteResult AddToCart(Cart cart, int gameId, string returnUrl)
        {
            var game = repository.Games.FirstOrDefault(g => g.GameId == gameId);
            if (game != null)
            {
                cart.AddItem(game, 1);
            }
            return RedirectToAction("Index", new {returnUrl});
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int gameId, string returnUrl)
        {
            var game = repository.Games.FirstOrDefault(g => g.GameId == gameId);
            if (game != null)
            {
                cart.RemoveItem(game);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            // if cart is empty
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry but your cart is empty");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

GameStore.WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Domain.Abstract;
using GameStore.WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        private IGameRepository repository;
        public int pageSize = 3;
        public GameController(IGameRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
        {
            var model = new GamesListViewModel
            {
                Games = repository.Games
                .Where(p => category == null || p.Category == category)
                .OrderBy(game => game.GameId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = repository.Games.Count(p => category == null || p.Category == category)
                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

GameStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Domain.Abstract;

namespace GameStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IGameRepository repository;

        public NavController(IGameRepository repo)
        {
            repository = repo;
        }
        // GET: Nav
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            var categories = repository.Games
                .Select(game => game.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

GameStore.WebUI/Views/Admin/Edit.cshtml
@model GameStore.Domain.Entities.Game

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    HtmlHelper.ClientValidationEnabled = false;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Admin"))
{
    <div class="panel-body">
        @Html.HiddenFor(m => m.GameId)
        @foreach (var property in ViewData.ModelMetadata.Properties.Where(property => property.PropertyName != "GameId"))
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @if (property.PropertyName == "Description")
                {
                    @Html.TextArea(property.PropertyName, null, new {@class = "form-control", rows = 5})
                }
                else
                {
                    @Html.TextBox(property.PropertyName, null, new {@class = "form-control"})
                }
                @Html.ValidationMessage(property.PropertyName)
            </div>
        }
    </div>
    <div class="panel-footer">
        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Cancel", "Index", new { @class = "btn btn-default"})
    </div>
    
}

GameStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<GameStore.Domain.Entities.Game>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Game List</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">
                    ID
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th class="text-center">
                    Actions
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.GameId</td>
                    <td>
                        @Html.ActionLink(item.Name, "Edit", new {item.GameId})
                    </td>
                    <td class="text-right">
                        @item.Price.ToString("# uah")
                    </td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("GameId", item.GameId)
                            <input type="submit" class="btn btn-default" value="Delete"/>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add game", "Create", null, new { @class = "btn btn-default"})
    </div>
</div>

GameStore.WebUI/Views/Cart/Checkout.cshtml
@model GameStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "GameStore: Shipping details";
}

<h2>Process your order</h2>
<p>Please enter your shipping information</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <h3>Data</h3>
    <div class="form-group">
        <label>Name</label>
        @Html.TextBoxFor(x => x.Name, new {@class = "form-control"})
    </div>

    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control"})
            </div>
        }
    }

    <h3>Options</h3>
    <div class="checkbox">
        <label>Use gift wrap: @Html.EditorFor(x => x.GiftWrap)</label>
    </div>

    @*<div class="form-group">
        <label>Name</label>
        @Html.TextBoxFor(x => x.Name, new {@class = "form-control"})
    </div>

    <div class="form-group">
        <label>First Address</label>
        @Html.TextBoxFor(x => x.Line1, new {@class = "form-control"})
    </div>

    <div class="form-group">
        <label>Second Address</label>
        @Html.TextBoxFor(x => x.Line2, new {@class = "form-control"})
    </div>

    <div class="form-group">
        <label>City</label>
        @Html.TextBoxFor(x => x.City, new {@class = "form-control"})
    </div>

    <div class="form-group">
        <label>Country</label>
        @Html.TextBoxFor(x => x.Country, new {@class = "form-control"})
    </div>

    <h3>Options</h3>
    <div class="checkbox">
        <label>Use gift wrap: @Html.EditorFor(x => x.GiftWrap)</label>
    </div>*@

    <input class="btn btn-primary" type="submit" value="Process"/>
}

GameStore.WebUI/Views/Cart/Completed.cshtml
@{ ViewBag.Title = "Order Processed";}

<h2>Your order has been processed</h2>

GameStore.WebUI/Views/Cart/Index.cshtml
@model GameStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Gamestore: Cart";
}


<h2>Your Cart</h2>

<table class="table">
    <thead>
    <tr>
        <th>Quantity</th>
        <th>Game name</th>
        <th class="text-right">Price</th>
        <th class="text-right">Total Price</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var cartLine in Model.Cart.Lines)
    {
        <tr>
            <td class="text-center">@cartLine.Quantity</td>
            <td class="text-left">@cartLine.Game.Name</td>
            <td class="text-right">@cartLine.Game.Price.ToString("# uah")</td>
            <td class="text-right">@((cartLine.Game.Price*cartLine.Quantity).ToString("# uah"))</td>
            <td>
                @using (Html.BeginForm("RemoveFromCart", "Cart"))
                {
                    @Html.Hidden("GameId", cartLine.Game.GameId)
                    @Html.HiddenFor(x => x.ReturnUrl)
                    <input type="submit" value="Delete" class="btn btn-sm btn-warning"/>
                }
            </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3" class="text-right">Total Price:</td>
        <td class="text-right">@Model.Cart.ComputeTotalPrice().ToString("# uah")</td>
    </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping...</a>
    @Html.ActionLink("Process your order", "Checkout", null, new { @class = "btn btn-primary" })
</div>

GameStore.WebUI/Views/Cart/Summary.cshtml
@model GameStore.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Order", "Index", "Cart",
        new {returnUrl = Request.Url.PathAndQuery},
        new {@class = "btn btn-default navbar-btn"})
</div>

<div class="navbar-text navbar-right">
    <b>Your Cart:</b>
    @Model.Lines.Sum(x => x.Quantity) items.
    @Model.ComputeTotalPrice().ToString("# uah")
</div>

GameStore.WebUI/Views/Game/List.cshtml
@using GameStore.WebUI.HtmlHelpers
@using GameStore.WebUI.Models
@model GamesListViewModel

@{
    ViewBag.Title = "Товары";
}

@foreach (var p in @Model.Games)
{
    @Html.Partial("GameSummary", p)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new
    {
        page = x,
        category = Model.CurrentCategory
    }))
</div>

GameStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@{
    string classStyle = "btn btn-block btn-default btn-lg";
}

@Html.ActionLink("Home", "List", "Game", null,
    new { @class = ViewBag.SelectedCategory == null ? classStyle + " btn-primary" : classStyle })


@foreach (var item in Model)
{
    @Html.RouteLink(item, new
{
    controller = "Game",
    action = "List",
    category = item,
    page = 1
}, new { @class = item == ViewBag.SelectedCategory ? classStyle + " btn-primary" : classStyle })
}

GameStore.WebUI/Views/Shared/GameSummary.cshtml
@model GameStore.Domain.Entities.Game
<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# uah")</span>
    </h3>

    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.GameId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart"/>
        </div>
    }

    <span class="lead">@Model.Description</span>
</div>

GameStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
<div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</div>
</body>
</html>

GameStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Game Store</a>
    @Html.Action("Summary", "Cart")
</div>
<div class="container">
    <div class="row panel">
        <div id="categories" class="col-xs-3">@Html.Action("Menu", "Nav")</div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</div>
</body>
</html>